### ISSUE TITLE
Extenso para metragem

### ISSUE THREAD

**Issue by aclimarin** [gimoteco/EscritaPorExtenso#12]
Olá, encontrei essa ótima biblioteca, mas senti falta de uma funcionalidade para transformar em extenso valores correspondente a metragens (m²: metros quadrados). Adicionei uma classe para isso que consegui usar sem grandes esforços.

`namespace EscritaPorExtenso.Metragem
{
    internal class MetroQuadrado
    {
        Classe _parteInteira;
        Classe _parteDecimal;
        private string _pluralidadeInteira;
        private string _pluralidadeDecimal;

        public MetroQuadrado(decimal valor)
        {
            var numeroDaParteInteira = (long)Math.Truncate(valor);

            if (numeroDaParteInteira > 0)
            {
                _parteInteira = ConversorDeNumeroParaClasses.Converter(numeroDaParteInteira);
                _pluralidadeInteira = ObterPluralidadeDaParteInteira(numeroDaParteInteira);
            }

            var parteDecimal = ((valor - Math.Truncate(valor)) * 100);

            var numeroDaParteDecimal = (long)parteDecimal;

            if (numeroDaParteDecimal > 0)
            {
                _parteDecimal = ConversorDeNumeroParaClasses.Converter(numeroDaParteDecimal);
                _pluralidadeDecimal = ObterPluralidadeDaParteDecimal(numeroDaParteDecimal);
            }
        }

        private static string ObterPluralidadeDaParteInteira(long parteInteira)
        {
            return parteInteira > 1 ? "metros quadrados" : "metro quadrado";
        }

        private static string ObterPluralidadeDaParteDecimal(long numeroDaParteDecimal)
        {
            return numeroDaParteDecimal > 1 ? "decímetros quadrados" : "decímetro quadrado";
        }

        public override string ToString()
        {
            string parteInteira = string.Format("{0} {1}", _parteInteira, _pluralidadeInteira);
            string parteDecimal = string.Format("{0} {1}", _parteDecimal, _pluralidadeDecimal);

            if (_parteDecimal != null && _parteInteira != null)
                return string.Format("{0} e {1}", parteInteira, parteDecimal);

            if (_parteDecimal != null)
                return parteDecimal;

            if (_parteInteira != null)
                return parteInteira;

            return "zero metro quadrado";
        }
    }
}
`
O único problema é que para valores decimais, a parte decimal só faz a conversão da primeira dezena. Exemplo:

Valor: 50,**253**
Resultado: cinquenta metros quadrados e **vinte e cinco** decímetros quadrados

**Comment by gimoteco** [comment]
Olá, obrigado pela sua sugestão, seria extremamente bem vinda uma contribuição com o extenso para m² com um pull request. Acho q isso que vc relatou acontece devido a multiplicação por 100 q se só vai deslocar a virgula em 2 casas.

**Comment by aclimarin** [comment]
Ok, vou testar aqui e vou fazer um pull request. Obrigada!

**Comment by aclimarin** [comment]
Fiz o pull request. 
Tenho uma dúvida: a partir do momento que o fonte for atualizado, é atualizada tb a versão que se baixa do nuget do visual studio?
Obrigada.

**Comment by gimoteco** [comment]
Não recebi o pull request aqui no repo. Quando for mergeado a build automatizada vai criar uma versão automaticamente
